// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// NewCheckCubeParams creates a new CheckCubeParams object
// with the default values initialized.
func NewCheckCubeParams() *CheckCubeParams {
	var ()
	return &CheckCubeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckCubeParamsWithTimeout creates a new CheckCubeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckCubeParamsWithTimeout(timeout time.Duration) *CheckCubeParams {
	var ()
	return &CheckCubeParams{

		timeout: timeout,
	}
}

// NewCheckCubeParamsWithContext creates a new CheckCubeParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckCubeParamsWithContext(ctx context.Context) *CheckCubeParams {
	var ()
	return &CheckCubeParams{

		Context: ctx,
	}
}

// NewCheckCubeParamsWithHTTPClient creates a new CheckCubeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckCubeParamsWithHTTPClient(client *http.Client) *CheckCubeParams {
	var ()
	return &CheckCubeParams{
		HTTPClient: client,
	}
}

/*CheckCubeParams contains all the parameters to send to the API endpoint
for the check cube operation typically these are written to a http.Request
*/
type CheckCubeParams struct {

	/*Request
	  Cube to be checked with the license should be used to check. License available amount will be reduced according to the cube volume.

	*/
	Request *model.Check

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check cube params
func (o *CheckCubeParams) WithTimeout(timeout time.Duration) *CheckCubeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check cube params
func (o *CheckCubeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check cube params
func (o *CheckCubeParams) WithContext(ctx context.Context) *CheckCubeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check cube params
func (o *CheckCubeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check cube params
func (o *CheckCubeParams) WithHTTPClient(client *http.Client) *CheckCubeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check cube params
func (o *CheckCubeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the check cube params
func (o *CheckCubeParams) WithRequest(request *model.Check) *CheckCubeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the check cube params
func (o *CheckCubeParams) SetRequest(request *model.Check) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CheckCubeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
