// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// DigCubeReader is a Reader for the DigCube structure.
type DigCubeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DigCubeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDigCubeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 402:
		result := NewDigCubePaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDigCubeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDigCubeOK creates a DigCubeOK with default headers values
func NewDigCubeOK() *DigCubeOK {
	return &DigCubeOK{}
}

/*DigCubeOK handles this case with default header values.

list of treasures found
*/
type DigCubeOK struct {
	Payload model.Treasures
}

func (o *DigCubeOK) Error() string {
	return fmt.Sprintf("[POST /dig][%d] digCubeOK  %+v", 200, o.Payload)
}

func (o *DigCubeOK) GetPayload() model.Treasures {
	return o.Payload
}

func (o *DigCubeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDigCubePaymentRequired creates a DigCubePaymentRequired with default headers values
func NewDigCubePaymentRequired() *DigCubePaymentRequired {
	return &DigCubePaymentRequired{}
}

/*DigCubePaymentRequired handles this case with default header values.

Not enough money
*/
type DigCubePaymentRequired struct {
}

func (o *DigCubePaymentRequired) Error() string {
	return fmt.Sprintf("[POST /dig][%d] digCubePaymentRequired ", 402)
}

func (o *DigCubePaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDigCubeInternalServerError creates a DigCubeInternalServerError with default headers values
func NewDigCubeInternalServerError() *DigCubeInternalServerError {
	return &DigCubeInternalServerError{}
}

/*DigCubeInternalServerError handles this case with default header values.

Internal Server Error
*/
type DigCubeInternalServerError struct {
}

func (o *DigCubeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dig][%d] digCubeInternalServerError ", 500)
}

func (o *DigCubeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
