// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// NewDigCubeParams creates a new DigCubeParams object
// with the default values initialized.
func NewDigCubeParams() *DigCubeParams {
	var ()
	return &DigCubeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDigCubeParamsWithTimeout creates a new DigCubeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDigCubeParamsWithTimeout(timeout time.Duration) *DigCubeParams {
	var ()
	return &DigCubeParams{

		timeout: timeout,
	}
}

// NewDigCubeParamsWithContext creates a new DigCubeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDigCubeParamsWithContext(ctx context.Context) *DigCubeParams {
	var ()
	return &DigCubeParams{

		Context: ctx,
	}
}

// NewDigCubeParamsWithHTTPClient creates a new DigCubeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDigCubeParamsWithHTTPClient(client *http.Client) *DigCubeParams {
	var ()
	return &DigCubeParams{
		HTTPClient: client,
	}
}

/*DigCubeParams contains all the parameters to send to the API endpoint
for the dig cube operation typically these are written to a http.Request
*/
type DigCubeParams struct {

	/*Request
	  Cube to be digged with the license should be charged.

	*/
	Request *model.Dig

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dig cube params
func (o *DigCubeParams) WithTimeout(timeout time.Duration) *DigCubeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dig cube params
func (o *DigCubeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dig cube params
func (o *DigCubeParams) WithContext(ctx context.Context) *DigCubeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dig cube params
func (o *DigCubeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dig cube params
func (o *DigCubeParams) WithHTTPClient(client *http.Client) *DigCubeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dig cube params
func (o *DigCubeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the dig cube params
func (o *DigCubeParams) WithRequest(request *model.Dig) *DigCubeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the dig cube params
func (o *DigCubeParams) SetRequest(request *model.Dig) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *DigCubeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
