// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// NewObtainLicensesParams creates a new ObtainLicensesParams object
// with the default values initialized.
func NewObtainLicensesParams() *ObtainLicensesParams {
	var ()
	return &ObtainLicensesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewObtainLicensesParamsWithTimeout creates a new ObtainLicensesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewObtainLicensesParamsWithTimeout(timeout time.Duration) *ObtainLicensesParams {
	var ()
	return &ObtainLicensesParams{

		timeout: timeout,
	}
}

// NewObtainLicensesParamsWithContext creates a new ObtainLicensesParams object
// with the default values initialized, and the ability to set a context for a request
func NewObtainLicensesParamsWithContext(ctx context.Context) *ObtainLicensesParams {
	var ()
	return &ObtainLicensesParams{

		Context: ctx,
	}
}

// NewObtainLicensesParamsWithHTTPClient creates a new ObtainLicensesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewObtainLicensesParamsWithHTTPClient(client *http.Client) *ObtainLicensesParams {
	var ()
	return &ObtainLicensesParams{
		HTTPClient: client,
	}
}

/*ObtainLicensesParams contains all the parameters to send to the API endpoint
for the obtain licenses operation typically these are written to a http.Request
*/
type ObtainLicensesParams struct {

	/*Amounts
	  Array of amounts for the licenses ordered.

	*/
	Amounts model.Amounts

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the obtain licenses params
func (o *ObtainLicensesParams) WithTimeout(timeout time.Duration) *ObtainLicensesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the obtain licenses params
func (o *ObtainLicensesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the obtain licenses params
func (o *ObtainLicensesParams) WithContext(ctx context.Context) *ObtainLicensesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the obtain licenses params
func (o *ObtainLicensesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the obtain licenses params
func (o *ObtainLicensesParams) WithHTTPClient(client *http.Client) *ObtainLicensesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the obtain licenses params
func (o *ObtainLicensesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAmounts adds the amounts to the obtain licenses params
func (o *ObtainLicensesParams) WithAmounts(amounts model.Amounts) *ObtainLicensesParams {
	o.SetAmounts(amounts)
	return o
}

// SetAmounts adds the amounts to the obtain licenses params
func (o *ObtainLicensesParams) SetAmounts(amounts model.Amounts) {
	o.Amounts = amounts
}

// WriteToRequest writes these params to a swagger request
func (o *ObtainLicensesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Amounts != nil {
		if err := r.SetBodyParam(o.Amounts); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
