swagger: '2.0'

info:
  title: HighLoad Cup 2020
  version: 0.0.1
  description: |
    # IT RALLY 2020 HighLoad Cup
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json


definitions:
  number:
    description: number
    type: integer
  amount:
    description: amount
    type: integer
  amounts:
    description: list of amounts
    type: array
    items:
      $ref: '#/definitions/amount'
  license:
    type: object
    properties:
      id:
        type: string
      remain:
        $ref: '#/definitions/amount'
  licenses:
    description: list of licenses issued
    type: array
    items:
      $ref: '#/definitions/license'
  position:
    type: object
    properties:
      'x':
        type: integer
      'y':
        type: integer
      'height':
        type: integer
      'width':
        type: integer
  check:
    type: object
    properties:
      license:
        type: string
      position:
        $ref: '#/definitions/position'
  dig:
    type: object
    properties:
      license:
        type: string
        description: ID of the license this request is attached to.
      full:
        type: boolean
        description: Should the whole cube be digged. Request will stop on the first treasure found if false.
      position:
        $ref: '#/definitions/position'
  treasure:
    type: string
    description: treasure ID to be cashed
  treasures:
    description: list of treasure IDs
    type: array
    items:
      $ref: '#/definitions/treasure'

responses:
  balance:
    description: balance
    schema:
      $ref: '#/definitions/amount'
  amounts:
    description: list of amounts
    schema:
      $ref: '#/definitions/amounts'
  licenses:
    description: list of licenses issued
    schema:
      $ref: '#/definitions/licenses'
  check:
    description: number of objects (treasures or even rocks) found
    schema:
      $ref: '#/definitions/number'
  dig:
    description: list of treasures found
    schema:
      $ref: '#/definitions/treasures'
  err500:
    description: Internal Server Error
  err402:
    description: Not enough money

paths:
  /balance:
    get:
      operationId: getBalance
      description: Returns a current balance.
      responses:
        '200': { $ref: '#/responses/balance' }
        '500': { $ref: '#/responses/err500' }
  /licenses:
    get:
      operationId: listLicenses
      description: Returns a list of currently provided licenses.
      responses:
        '200': { $ref: '#/responses/licenses' }
        '500': { $ref: '#/responses/err500' }
    post:
      operationId: obtainLicense
      description: Returns a newly created license.
      parameters:
        - name: amount
          description: Amount to spend for a license.
          required: true
          in: body
          schema:
            $ref: '#/definitions/amount'
      responses:
        '200': { $ref: '#/responses/licenses' }
        '402': { $ref: '#/responses/err402' }
        '500': { $ref: '#/responses/err500' }
  /check:
    post:
      operationId: checkCube
      description: Returns number of treasures in the provided cube.
      parameters:
        - name: request
          description: Cube to be checked with the license should be used to check. License available amount will be reduced according to the cube volume.
          required: true
          in: body
          schema:
            $ref: '#/definitions/check'
      responses:
        '200': { $ref: '#/responses/check' }
        '402': { $ref: '#/responses/err402' }
        '500': { $ref: '#/responses/err500' }
  /dig:
    post:
      operationId: digCube
      description: Returns a list of found treasures IDs.
      parameters:
        - name: request
          description: Cube to be digged with the license should be charged.
          required: true
          in: body
          schema:
            $ref: '#/definitions/dig'
      responses:
        '200': { $ref: '#/responses/dig' }
        '402': { $ref: '#/responses/err402' }
        '500': { $ref: '#/responses/err500' }
  /cash:
    post:
      operationId: cash
      description: Returns a list of found treasures IDs.
      parameters:
        - name: request
          description: .
          required: true
          in: body
          schema:
            $ref: '#/definitions/treasures'
      responses:
        '201':
          description: Cashed
        '500': { $ref: '#/responses/err500' }

