// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Amount amount
//
// swagger:model amount
type Amount int64

// Validate validates this amount
func (m Amount) Validate(formats strfmt.Registry) error {
	return nil
}
