// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Number number
//
// swagger:model number
type Number int64

// Validate validates this number
func (m Number) Validate(formats strfmt.Registry) error {
	return nil
}
