// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Treasure treasure ID to be cashed
//
// swagger:model treasure
type Treasure string

// Validate validates this treasure
func (m Treasure) Validate(formats strfmt.Registry) error {
	return nil
}
