// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Wallet Wallet with some amount of money.
//
// swagger:model wallet
type Wallet []string

// Validate validates this wallet
func (m Wallet) Validate(formats strfmt.Registry) error {
	return nil
}
