// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// CashCreatedCode is the HTTP code returned for type CashCreated
const CashCreatedCode int = 201

/*CashCreated Cashed

swagger:response cashCreated
*/
type CashCreated struct {
}

// NewCashCreated creates CashCreated with default headers values
func NewCashCreated() *CashCreated {

	return &CashCreated{}
}

// WriteResponse to the client
func (o *CashCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

func (o *CashCreated) CashResponder() {}

// CashInternalServerErrorCode is the HTTP code returned for type CashInternalServerError
const CashInternalServerErrorCode int = 500

/*CashInternalServerError Internal Server Error

swagger:response cashInternalServerError
*/
type CashInternalServerError struct {
}

// NewCashInternalServerError creates CashInternalServerError with default headers values
func NewCashInternalServerError() *CashInternalServerError {

	return &CashInternalServerError{}
}

// WriteResponse to the client
func (o *CashInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *CashInternalServerError) CashResponder() {}

type CashNotImplementedResponder struct {
	middleware.Responder
}

func (*CashNotImplementedResponder) CashResponder() {}

func CashNotImplemented() CashResponder {
	return &CashNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Cash has not yet been implemented",
		),
	}
}

type CashResponder interface {
	middleware.Responder
	CashResponder()
}
