// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// DigCubeOKCode is the HTTP code returned for type DigCubeOK
const DigCubeOKCode int = 200

/*DigCubeOK list of treasures found

swagger:response digCubeOK
*/
type DigCubeOK struct {

	/*
	  In: Body
	*/
	Payload model.Treasures `json:"body,omitempty"`
}

// NewDigCubeOK creates DigCubeOK with default headers values
func NewDigCubeOK() *DigCubeOK {

	return &DigCubeOK{}
}

// WithPayload adds the payload to the dig cube o k response
func (o *DigCubeOK) WithPayload(payload model.Treasures) *DigCubeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dig cube o k response
func (o *DigCubeOK) SetPayload(payload model.Treasures) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DigCubeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = model.Treasures{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *DigCubeOK) DigCubeResponder() {}

// DigCubePaymentRequiredCode is the HTTP code returned for type DigCubePaymentRequired
const DigCubePaymentRequiredCode int = 402

/*DigCubePaymentRequired Not enough money

swagger:response digCubePaymentRequired
*/
type DigCubePaymentRequired struct {
}

// NewDigCubePaymentRequired creates DigCubePaymentRequired with default headers values
func NewDigCubePaymentRequired() *DigCubePaymentRequired {

	return &DigCubePaymentRequired{}
}

// WriteResponse to the client
func (o *DigCubePaymentRequired) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(402)
}

func (o *DigCubePaymentRequired) DigCubeResponder() {}

// DigCubeInternalServerErrorCode is the HTTP code returned for type DigCubeInternalServerError
const DigCubeInternalServerErrorCode int = 500

/*DigCubeInternalServerError Internal Server Error

swagger:response digCubeInternalServerError
*/
type DigCubeInternalServerError struct {
}

// NewDigCubeInternalServerError creates DigCubeInternalServerError with default headers values
func NewDigCubeInternalServerError() *DigCubeInternalServerError {

	return &DigCubeInternalServerError{}
}

// WriteResponse to the client
func (o *DigCubeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *DigCubeInternalServerError) DigCubeResponder() {}

type DigCubeNotImplementedResponder struct {
	middleware.Responder
}

func (*DigCubeNotImplementedResponder) DigCubeResponder() {}

func DigCubeNotImplemented() DigCubeResponder {
	return &DigCubeNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DigCube has not yet been implemented",
		),
	}
}

type DigCubeResponder interface {
	middleware.Responder
	DigCubeResponder()
}
