// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// GetAccountOKCode is the HTTP code returned for type GetAccountOK
const GetAccountOKCode int = 200

/*GetAccountOK amount

swagger:response getAccountOK
*/
type GetAccountOK struct {

	/*
	  In: Body
	*/
	Payload model.Amount `json:"body,omitempty"`
}

// NewGetAccountOK creates GetAccountOK with default headers values
func NewGetAccountOK() *GetAccountOK {

	return &GetAccountOK{}
}

// WithPayload adds the payload to the get account o k response
func (o *GetAccountOK) WithPayload(payload model.Amount) *GetAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account o k response
func (o *GetAccountOK) SetPayload(payload model.Amount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *GetAccountOK) GetAccountResponder() {}

// GetAccountInternalServerErrorCode is the HTTP code returned for type GetAccountInternalServerError
const GetAccountInternalServerErrorCode int = 500

/*GetAccountInternalServerError Internal Server Error

swagger:response getAccountInternalServerError
*/
type GetAccountInternalServerError struct {
}

// NewGetAccountInternalServerError creates GetAccountInternalServerError with default headers values
func NewGetAccountInternalServerError() *GetAccountInternalServerError {

	return &GetAccountInternalServerError{}
}

// WriteResponse to the client
func (o *GetAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *GetAccountInternalServerError) GetAccountResponder() {}

type GetAccountNotImplementedResponder struct {
	middleware.Responder
}

func (*GetAccountNotImplementedResponder) GetAccountResponder() {}

func GetAccountNotImplemented() GetAccountResponder {
	return &GetAccountNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetAccount has not yet been implemented",
		),
	}
}

type GetAccountResponder interface {
	middleware.Responder
	GetAccountResponder()
}
