// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// ListLicensesOKCode is the HTTP code returned for type ListLicensesOK
const ListLicensesOKCode int = 200

/*ListLicensesOK list of licenses issued

swagger:response listLicensesOK
*/
type ListLicensesOK struct {

	/*
	  In: Body
	*/
	Payload model.Licenses `json:"body,omitempty"`
}

// NewListLicensesOK creates ListLicensesOK with default headers values
func NewListLicensesOK() *ListLicensesOK {

	return &ListLicensesOK{}
}

// WithPayload adds the payload to the list licenses o k response
func (o *ListLicensesOK) WithPayload(payload model.Licenses) *ListLicensesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list licenses o k response
func (o *ListLicensesOK) SetPayload(payload model.Licenses) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListLicensesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = model.Licenses{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *ListLicensesOK) ListLicensesResponder() {}

// ListLicensesInternalServerErrorCode is the HTTP code returned for type ListLicensesInternalServerError
const ListLicensesInternalServerErrorCode int = 500

/*ListLicensesInternalServerError Internal Server Error

swagger:response listLicensesInternalServerError
*/
type ListLicensesInternalServerError struct {
}

// NewListLicensesInternalServerError creates ListLicensesInternalServerError with default headers values
func NewListLicensesInternalServerError() *ListLicensesInternalServerError {

	return &ListLicensesInternalServerError{}
}

// WriteResponse to the client
func (o *ListLicensesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *ListLicensesInternalServerError) ListLicensesResponder() {}

type ListLicensesNotImplementedResponder struct {
	middleware.Responder
}

func (*ListLicensesNotImplementedResponder) ListLicensesResponder() {}

func ListLicensesNotImplemented() ListLicensesResponder {
	return &ListLicensesNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ListLicenses has not yet been implemented",
		),
	}
}

type ListLicensesResponder interface {
	middleware.Responder
	ListLicensesResponder()
}
