// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Djarvur/allcups-itrally-2020-task/api/openapi/model"
)

// NewObtainLicensesParams creates a new ObtainLicensesParams object
// no default values defined in spec.
func NewObtainLicensesParams() ObtainLicensesParams {

	return ObtainLicensesParams{}
}

// ObtainLicensesParams contains all the bound params for the obtain licenses operation
// typically these are obtained from a http.Request
//
// swagger:parameters obtainLicenses
type ObtainLicensesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Array of amounts for the licenses ordered.
	  Required: true
	  In: body
	*/
	Amounts model.Amounts
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewObtainLicensesParams() beforehand.
func (o *ObtainLicensesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body model.Amounts
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("amounts", "body", ""))
			} else {
				res = append(res, errors.NewParseError("amounts", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Amounts = body
			}
		}
	} else {
		res = append(res, errors.Required("amounts", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
