// Code generated by go-swagger; DO NOT EDIT.

// Package restapi HighLoad Cup 2020
//
//  # IT RALLY 2020 HighLoad Cup
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.2.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
